version: '3'

services:
  php-apache:
    build:
    context:
    dockerfile: Dockerfile
  ports:
    - "80:80"
  volumes:
    - .:/var/www/html
environment:
      - DBNAME=${DBNAME}  # These will come from Render's environment variables
      - HOST=${HOST}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - PORT=${PORT}  # Port 5432 will be provided by Render