version: '3'

services:
  php-apache:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Web server port
    volumes:
      - .:/var/www/html
    environment:
      - DBNAME=${DBNAME}
      - HOST=${HOST}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - PORT=${PORT}  # Ensure 5432 for PostgreSQL